---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "wallix-bastion_config_x509 Resource - terraform-provider-wallix-bastion"
subcategory: ""
description: |-
  Provides a X509 resource for configuring X509 authentication and certificates.
---

# wallix-bastion_config_x509 (Resource)

Provides a X509 resource for configuring X509 authentication and/or changing GUI and API certificates.

## Example Usage

```terraform
# Configure the X509 authentication and/or change GUI and API certificates
resource "wallix-bastion_config_x509" "acme-cert" {
  ca_certificate     = file("${path.root}/chain1.pem")
  server_private_key = file("${path.root}/privkey1.pem")
  server_public_key  = file("${path.root}/cert1.pem")
  enable             = true
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `server_private_key` (String) The server certificate private key
- `server_public_key` (String) The server certificate public key

### Optional

- `ca_certificate` (String) The ca for users authentication
- `enable` (Boolean) Whether or not enable X509 users authentication

### Read-Only

- `id` (String) Internal id of X509 config (only in Tfstate since the API does not provide any)

## Import

X509 config can be imported using any id (in Tfstate it will always be x509Config) e.g.

```shell
terraform import wallix-bastion_config_x509.acme-cert myx509
```
